[font]
normal={ family='JetBrainsMono Nerd Font'}
size=12
[mouse]
hide_when_typing=true
[terminal]
shell = "nu"
# [colors.primary]
# background = "#282C34"

[keyboard]
bindings = [
  { key = 1, mods = "Control", chars = "\u00130" },
  { key = 2, mods = "Control", chars = "\u00131" },
  { key = 3, mods = "Control", chars = "\u00132" },
  { key = 4, mods = "Control", chars = "\u00133" },
  { key = 5, mods = "Control", chars = "\u00134" },
]



