theme='ayu_mirage'

[editor]
line-number='relative'
auto-completion=true
auto-format=false
clipboard-provider='wayland'
shell = ['nu',"--config", "~/.config/nushell/config.nu", "-c"]
cursorline =true
continue-comments = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal.space]
f = "@<space>F<C-t>"
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
x = ":sh tmux new-window -n fx '~/.local/bin/yazi-picker.sh open'"

