[[language]]
name = "python"
# language-servers = [ "basedpyright" ]

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python"
args = ["-m",  "debugpy.adapter"]
[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }
# [language-server.basedpyright]
# command = "basedpyright-langserver"
# args = ["--stdio"]
#
# [language-server.basedpyright.config]
# basedpyright.analysis.diagnosticMode = "openFilesOnly"
