[opener]
edit = [
	{ run = 'nvim --remote "$@"', block = true, for = "unix" },
]

[[opener.set-wallpaper]]
run  = 'killall swaybg; swaybg -m fill -i "$1"'
for  = "linux"
desc = "Set as wallpaper"
orphan = true

# [[open.prepend_rules]]
# mime = "image/*"
# use  = [ "set-wallpaper", "open" ]

